language: ruby
rvm:
  - 2.5.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
after_success:
  - docker build -t epotter22/equipo-wiki .
  - docker login -u epotter22 -p '|34ccwLF(LY|'
  - docker push epotter22/equipo-wiki
branches:
  only:
  - master